name: build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: neilotoole/xcgo:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Sync vendor directory
        working-directory: ./goleveldb
        run: |
          go mod vendor
        shell: bash
      - name: Build
        working-directory: ./goleveldb
        run: |
          ./build.sh
        shell: bash
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Nexus Repository Publisher for GitHub Actions
        uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
        with:
          serverUrl: https://nexus.stirante.com
          username: admin
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: maven-snapshots
          coordinates: groupId=nl.itslars artifactId=kosmos version=1.1.5-SNAPSHOT
          assets: extension=jar
          filename: ./target/kosmos-1.1.4.jar