name: build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Set up Zig
        run: |
          brew install zig
      - name: Sync vendor directory
        run: |
          go mod vendor
        shell: bash
      - name: Build
        working-directory: ./goleveldb
        run: |
          ./build.sh
        shell: bash
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package